quarkus:
  test:
    continuous-testing: disabled
  live-reload:
    instrumentation: true
  http:
    auth:
      proactive: false
    port: 8888
  #     把404继续传递
  rest:
    resume-on404: true
  #    quinoa:
#    dev-server: false
#    build-dir: dist
#    ui-root-path: "quinoa"
#    package-manager: npm
#    package-manager-install:
#      install-dir: D:\NodeJS
#      node-version: 20.19.2
#      npm-version: 11.4.2
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    log:
      sql: false
#      打印带参数的sql
      bind-parameters: false
    database:
      generation: none
    validate-in-dev-mode: false
    sql-load-script: import.sql
  datasource:
    username: hanford
    password: 9632147890aA
    reactive:
      url: mysql://113.45.143.70:3306/short_link?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    db-kind: mysql
  log:
    level: INFO
    category:
      "com.deevvi.device.detector.engine.loader.Loader":
        level: error
snowflake:
  worker-id: 1
  datacenter-id: 1
short-link:
  segment:
    initial-value: 100000
    step: 1000
    prefetch-threshold: 100

smallrye:
  jwt:
    sign:
      key:
        location: META-INF/resources/private_key.pem
    encrypt:
      key:
        location: META-INF/resources/public_key.pem
mp:
  jwt:
    verify:
      publickey:
        location: META-INF/resources/public_key.pem
